language: python
python:
    - "2.7"
env:
    - CKANVERSION=2.7
install:
    - bash bin/travis-build.bash
services:
    - postgresql: 9.3
    - mongodb
script: sh bin/travis-run.sh
after_success: coveralls
sudo: required