dist: xenial
language: python
python:
  - "2.7"
env:
  - CKANVERSION=master
install:
  - bash bin/travis-build.bash
services:
  - mongodb
  - postgresql

env:
  global:
  - PGPORT=5432

script: sh bin/travis-run.sh
after_success: coveralls
sudo: required